"""
cyk_algorithm.py - CYK (Cocke-Younger-Kasami) Algorithm
=========================================================
This module implements the CYK algorithm for checking whether
a given string belongs to the language generated by a CFG in CNF.

The CYK Algorithm:
    - Uses dynamic programming (bottom-up parsing)
    - Builds a triangular table T[i][j] where each cell contains
      the set of non-terminals that can derive the substring w[i..j]
    - The string is accepted if the start symbol is in T[0][n-1]

Time Complexity: O(n³ · |G|) where n = |w| and |G| = grammar size
Space Complexity: O(n² · |N|) where |N| = number of non-terminals
"""


def cyk_algorithm(cnf_productions, start_symbol, input_string, non_terminals):
    """
    Run the CYK algorithm to determine if input_string ∈ L(G).

    Args:
        cnf_productions (dict): Grammar in CNF {NT: [[sym1, sym2], [sym], ...]}
        start_symbol (str): The start symbol of the CNF grammar
        input_string (str): The string to check for membership
        non_terminals (set): Set of non-terminal symbols

    Returns:
        tuple: (accepted, table, steps)
            - accepted (bool): True if the string is in the language
            - table (list of list of set): The CYK table T[i][j]
            - steps (list): Step-by-step log of the algorithm's execution
              Each step is a dict with keys:
                'phase': str ('init' | 'fill_cell'),
                'i': int, 'j': int,
                'description': str,
                'cell_value': set of non-terminal strings
    """
    n = len(input_string)
    steps = []

    # ---- Handle empty string ----
    if n == 0:
        # Check if start symbol can produce ε
        accepted = any(
            body == [] for body in cnf_productions.get(start_symbol, [])
        )
        steps.append({
            'phase': 'empty_string',
            'description': (
                f"Input string is empty (ε).\n"
                f"Checking if {start_symbol} → ε exists: "
                f"{'YES ✓' if accepted else 'NO ✗'}"
            ),
            'accepted': accepted
        })
        return accepted, [[]], steps

    # ---- Initialize the CYK table ----
    # table[i][j] = set of non-terminals that can derive w[i..j] (inclusive)
    table = [[set() for _ in range(n)] for _ in range(n)]

    # ===== PHASE 1: Fill diagonal (single characters) =====
    steps.append({
        'phase': 'header',
        'description': (
            "═══ Phase 1: Base Case (Single Characters) ═══\n"
            "For each character w[i], find all non-terminals A where A → w[i] exists."
        )
    })

    for i in range(n):
        char = input_string[i]
        # Find all non-terminals that produce this single terminal
        for nt in cnf_productions:
            for body in cnf_productions[nt]:
                if len(body) == 1 and body[0] == char:
                    table[i][i].add(nt)

        steps.append({
            'phase': 'init',
            'i': i,
            'j': i,
            'char': char,
            'description': (
                f"Cell [{i}][{i}]: Character '{char}'\n"
                f"  Non-terminals producing '{char}': "
                f"{_format_set(table[i][i]) if table[i][i] else '∅ (none)'}"
            ),
            'cell_value': set(table[i][i])
        })

    # ===== PHASE 2: Fill table bottom-up (substrings of increasing length) =====
    steps.append({
        'phase': 'header',
        'description': (
            "\n═══ Phase 2: Inductive Step (Longer Substrings) ═══\n"
            "For each substring w[i..j] of length ℓ (from 2 to n),\n"
            "try all split points k: check if A → BC where\n"
            "B ∈ table[i][k] and C ∈ table[k+1][j]."
        )
    })

    for length in range(2, n + 1):       # Length of the substring
        for i in range(n - length + 1):   # Start index
            j = i + length - 1             # End index

            derivation_details = []

            for k in range(i, j):          # Split point
                # Get non-terminals for the two halves
                left_set = table[i][k]     # Non-terminals deriving w[i..k]
                right_set = table[k+1][j]  # Non-terminals deriving w[k+1..j]

                if not left_set or not right_set:
                    continue

                # Check all productions A -> BC
                for nt in cnf_productions:
                    for body in cnf_productions[nt]:
                        if len(body) == 2:
                            B, C = body[0], body[1]
                            if B in left_set and C in right_set:
                                table[i][j].add(nt)
                                derivation_details.append(
                                    f"  {nt} → {B} {C}  "
                                    f"(B='{B}' ∈ [{i}][{k}], C='{C}' ∈ [{k+1}][{j}], split at k={k})"
                                )

            substring = input_string[i:j+1]
            desc = f"Cell [{i}][{j}]: Substring '{substring}' (length {length})\n"
            if derivation_details:
                desc += "  Found productions:\n" + '\n'.join(derivation_details) + "\n"
            desc += (
                f"  Result: {_format_set(table[i][j]) if table[i][j] else '∅ (empty)'}"
            )

            steps.append({
                'phase': 'fill_cell',
                'i': i,
                'j': j,
                'length': length,
                'description': desc,
                'cell_value': set(table[i][j])
            })

    # ===== FINAL RESULT =====
    accepted = start_symbol in table[0][n-1]
    steps.append({
        'phase': 'result',
        'description': (
            f"\n═══ Final Result ═══\n"
            f"Top-right cell [{0}][{n-1}] = {_format_set(table[0][n-1])}\n"
            f"Start symbol '{start_symbol}' "
            f"{'∈' if accepted else '∉'} table[0][{n-1}]\n"
            f"\n  ➤ String '{input_string}' is "
            f"{'✓ ACCEPTED' if accepted else '✗ REJECTED'}"
        ),
        'accepted': accepted
    })

    return accepted, table, steps


def format_cyk_table(table, input_string):
    """
    Format the CYK table as a readable string for display.

    The table is displayed as an upper-triangular matrix:
        Row i represents the starting position.
        Column j represents the ending position.
        Cell [i][j] shows non-terminals that derive w[i..j].

    Args:
        table: The CYK table (list of list of set)
        input_string: The input string

    Returns:
        str: Formatted table string
    """
    n = len(input_string)
    if n == 0:
        return "  (Empty string — no table to display)"

    # ---- Calculate column widths ----
    col_widths = []
    for j in range(n):
        max_w = max(
            len(_format_set(table[i][j])) if i <= j else 0
            for i in range(n)
        )
        max_w = max(max_w, 3, len(input_string[j]) + 2)  # Minimum width
        col_widths.append(max_w)

    # ---- Build the table ----
    lines = []

    # Header row (characters of the string)
    header = "       "  # Space for row labels
    for j in range(n):
        header += f"  {input_string[j]:^{col_widths[j]}}  "
    lines.append(header)

    # Column indices
    idx_row = "       "
    for j in range(n):
        idx_row += f"  {f'[{j}]':^{col_widths[j]}}  "
    lines.append(idx_row)

    # Separator
    lines.append("       " + "─" * (sum(col_widths) + 4 * n))

    # Data rows
    for i in range(n):
        row = f"  [{i}]  "
        for j in range(n):
            if i <= j:
                cell = _format_set(table[i][j]) if table[i][j] else "·"
                row += f"│ {cell:^{col_widths[j]}} │"
            else:
                row += f"  {'':^{col_widths[j]}}  "
        lines.append(row)

    return '\n'.join(lines)


def _format_set(s):
    """Format a set of non-terminals as a comma-separated string in braces."""
    if not s:
        return "∅"
    return "{" + ", ".join(sorted(s)) + "}"
